# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *

import pandas as pd
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import os
from matchcode import match_operation



class Ui_MainWindow(object):
    # def __init__(self):
    #     super(Ui_MainWindow, self).__init__()
    #     self.setupUi(self)
    #     self.retranslateUi(self)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 320, 891, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(223, 90, 31, 18))
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(250, 90, 111, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 120, 801, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.textEdit_5 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalLayout_2.addWidget(self.textEdit_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 49, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(213, 180, 31, 18))
        self.label_7.setObjectName("label_7")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(80, 180, 111, 21))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(250, 180, 111, 21))
        self.textEdit_7.setObjectName("textEdit_7")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 210, 801, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.textEdit_8 = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.textEdit_8.setObjectName("textEdit_8")
        self.horizontalLayout_3.addWidget(self.textEdit_8)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.operationButton = QtWidgets.QPushButton(self.centralwidget)
        self.operationButton.setGeometry(QtCore.QRect(880, 60, 111, 61))
        self.operationButton.setObjectName("operationButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(21, 34, 801, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(77, 90, 111, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 49, 18))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.msg_1)
        self.pushButton_2.clicked.connect(self.msg_2)
        self.pushButton_3.clicked.connect(self.msg_3)
        self.operationButton.clicked.connect(self.match_data)

    def match_data(self):
        filename_data = self.textEdit.toPlainText()
        filename_library = self.textEdit_5.toPlainText()
        column_data = int(self.textEdit_3.toPlainText())
        column_library = int(self.textEdit_7.toPlainText())
        save_finalData = self.textEdit_8.toPlainText()
        save_matchData = self.textEdit_8.toPlainText()
        match_operation(filename_data, filename_library, column_data, column_library, save_finalData, save_matchData)
        print("finish")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.label_4.setText(_translate("MainWindow", "列号"))
        self.label_5.setText(_translate("MainWindow", "库地址"))
        self.pushButton_2.setText(_translate("MainWindow", "选择文件"))
        self.label_6.setText(_translate("MainWindow", "Sheet名"))
        self.label_7.setText(_translate("MainWindow", "列号"))
        self.label_8.setText(_translate("MainWindow", "保存地址"))
        self.pushButton_3.setText(_translate("MainWindow", "选择文件"))
        self.operationButton.setText(_translate("MainWindow", "开始计算"))
        self.label.setText(_translate("MainWindow", "文件地址"))
        self.pushButton.setText(_translate("MainWindow", "选择文件"))
        self.label_2.setText(_translate("MainWindow", "Sheet名"))
        self.textEdit.setText(_translate("MainWindow", ""))
        self.textEdit_5.setText(_translate("MainWindow", ""))
        self.textEdit_8.setText(_translate("MainWindow", ""))

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据处理工具"))

        self.textEdit.setText(_translate("MainWindow", ""))

    def msg_1(self, Filepath):
        fileName, fileType = QtWidgets.QFileDialog.getOpenFileName(None, "选取文件", os.getcwd(),
                                                                   "All Files(*);;Text Files(*.txt)")
        self.textEdit.setText(str(fileName))

    def msg_2(self, Filepath):
        fileName, fileType = QtWidgets.QFileDialog.getOpenFileName(None, "选取文件", os.getcwd(),
                                                                   "All Files(*);;Text Files(*.txt)")
        self.textEdit_5.setText(str(fileName))

    def msg_3(self, Filepath):
        directory = QtWidgets.QFileDialog.getExistingDirectory(None, "选取文件夹", "C:/")  # 起始路径
        self.textEdit_8.setText(directory)




# class Tables(QMainWindow):
#     def table(self):
#         self.setupUi(self)
#         # 运行数据读取函数
#         self.dataprocess()
#         # 运行tableWidget初始化函数
#         self.initialize()
#         # 运行按钮的点击事件
#         self.saveButton.clicked.connect(self.save)
#
#     # 定义表格的初始化参数
#     def initialize(self):
#         # 设置表格行数和列数
#         self.tableWidget.setRowCount(len(self.rows))
#         self.tableWidget.setColumnCount(len(self.columns))
#         # 设置表格的列标签
#         self.tableWidget.setHorizontalHeaderLabels(self.columns)
#         # 重新设置表格区域的大小
#         self.tableWidget.setGeometry(QtCore.QRect(220, 120, 1000, 800))
#         # 将数据显示在表格中
#         for i in range(len(self.rows)):
#             for j in range(len(self.columns)):
#                 data = QTableWidgetItem(str(self.df.iloc[i][j]))
#                 self.tableWidget.setItem(i, j, data)
#         # 列宽随着内容调整
#         self.tableWidget.resizeColumnsToContents()
#         # 行宽随着内容调整
#         self.tableWidget.resizeRowsToContents()
#         # 表格颜色交错显示
#         self.tableWidget.setAlternatingRowColors(True)
#         # 将表格中单元格改变时，触发tableChange事件
#         self.tableWidget.itemChanged.connect(self.tableChange)
#
#     # 当表格的内容改变时获取内容
#     def tableChange(self, item):
#         text = item.text()
#         itemrow = item.row()
#         itemcol = item.column()
#         self.df.iloc[[itemrow], [itemcol]] = text
#
#     # 数据读取
#     def dataprocess(self):
#         save_finalData = self.textEdit_8.toPlainText()
#         self.df = pd.read_excel(save_finalData + '/匹配表.xlsx')
#         # 获得数据的行标签和列标签
#         self.columns = self.df.columns
#         self.rows = self.df.index
#
#     # 保存数据
#     def save(self):
#         save_finalData = self.textEdit_8.toPlainText()
#         self.df.to_excel(save_finalData + '/匹配表.xlsx', index=False)


# def msg_address(self):
#    address = self.textEdit_8.toPlainText() + '/匹配表.xlsx'
#    return address

# if __name__ == "__main__":
#     app = QApplication(sys.argv)
#     ui = Ui_MainWindow()
#     ui.show()
#     sys.exit(app.exec_())
